apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
spec:
  selector:
    app: fastapi
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
  type: LoadBalancer
  externalIPs:
  - 10.106.19.139
